name: Build and Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - run: go build -v ./...
      - run: go test -v ./...

  format:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - run: go mod tidy
      - run: go fmt ./...
      - run: git diff --exit-code --stat

  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: reviewdog/action-golangci-lint@v2

  go-releaser:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 1.23.0
          args: check
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 1.23.0
          args: build --snapshot --timeout 8m