name: Dependabot auto-merge

on: pull_request_target

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]'
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
      - if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ github.token }}
