name: goreleaser

on:
  workflow_dispatch:
    inputs:

  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  goreleaser:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v5
        if: >
          startsWith( github.ref, 'refs/tags/v' )
        with:
          distribution: goreleaser
          version: 1.14.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v5
        if: >
          !startsWith( github.ref, 'refs/tags/v' )
        with:
          distribution: goreleaser
          version: 1.14.0
          args: release --rm-dist --snapshot
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*